### ISSUE TITLE
Kamelon does not render nicely in Mac Safari

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kameleon#17]
<img width="1250" alt="Screenshot 2021-10-01 at 09 56 26" src="https://user-images.githubusercontent.com/477100/135585704-f89ac193-8212-4d1b-a8d7-9aa22cb8aee6.png">

**Comment by jamesnetherton** [comment]
Renders fine for me in `Version 15.0 (16612.1.29.41.4, 16612)`.

**Comment by davsclaus** [comment]
Version 14.0.3 (14610.4.3.1.7)

**Comment by davsclaus** [comment]
But a newer works fine: Version 14.1.2 (16611.3.10.1.6)

**Comment by davsclaus** [comment]
I guess people can update their browser
