### ISSUE TITLE
Replace mvn with camel-jbang

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-kameleon#26]
@davsclaus 
As an idea. If we use camel-jbang instead of maven, perhaps it will be faster and requites less resources than maven

**Comment by davsclaus** [comment]
Yeah that is a good idea, then its similar to karavan, and with jbang we have more a lot more power.
And we have synergy between kameleon and karavan.

**Comment by davsclaus** [comment]
duplicate of #37
